### ISSUE TITLE
Unit tests are hitting network and are not stubbed

### ISSUE THREAD

**Issue by serejahh** [MLSDev/TRON#21]
Hey! Thanks for the awesome lib. I'm just wondering why you don't use http stub library
1. It could decrease time for running tests (it takes me 91 sec for 374 tests)
1. It could make them isolated (now if you don't have internet connection or 3rd party service is down, they fail)

**Comment by DenTelezhkin** [comment]
Hey!

It's mostly a timing issue. It was an overhead for us to throw in stubbing library like OHHTTPStubs for example. For example, [Alamofire](https://github.com/Alamofire/Alamofire), which we are basing on, is also using network requests in unit tests.

Ideally, sure, there should be no network calls in unit tests, but it was faster for us to have usual network calls, especially because Travis CI is almost always online.

However, if you have time to help us with transition to stubbed network requests in unit tests, that would be really great.

**Comment by DenTelezhkin** [comment]
Hi, small update =) It's curious that we just celebrated 2nd anniversary of this issue, but anyway.

I've finally had some time to take a stab on this. I'm currently working on the next version of TRON, that will be released some time after Alamofire 5 release, and stubbed unit tests is one of the improvements I wanted to make.

This is finished in dd0161f79d79a750dd0512f28f355ed027caa3c5, and so next release of TRON will finally solve this issue. Again, thanks for bringing this up.

**Comment by serejahh** [comment]
Nice to hear 👍

**Comment by DenTelezhkin** [comment]
Released in https://github.com/MLSDev/TRON/releases/tag/5.0.0-beta.1 :shipit:

**Comment by serejahh** [comment]
🤘
