### ISSUE TITLE
Example using ObjectMapper with TRON

### ISSUE THREAD

**Issue by vegidio** [MLSDev/TRON#25]
Do you have any example of how to use TRON with ObjectMapper? (https://github.com/Hearst-DD/ObjectMapper)

Thanks

**Comment by DenTelezhkin** [comment]
We've had it in the past for the old version of TRON, but then it was removed - we had no time to support all example code.

It's however, a good stuff to have. I think in the future we need examples for most popular/fast mappers available - i think we would start from [Unbox](https://github.com/JohnSundell/Unbox) and ObjectMapper. However i don't know when we'll have time to do it - right now our workload is very high.

I'll leave this issue open as a reminder, in the meantime you can take a look at [SwiftyJSON part](https://github.com/MLSDev/TRON/blob/master/Source/SwiftyJSON/SwiftyJSONDecodable.swift). I think with ObjectMapper it will be extremely similar - you just need to use `Mappable` instead of `JSONDecodable` protocol.

**Comment by KarpenkoAV** [comment]
If you are using for the network library Alamofire, can I retrieve objects such as https://github.com/evermeer/AlamofireJsonToObjects
https://cocoapods.org/pods/AlamofireJsonToObjects

Thanks

**Comment by DenTelezhkin** [comment]
This issue looks stale. TRON supports `Codable` and `SwiftyJSON` out of the box, and all common parsers and mappers with some additional code.

Pull requests are welcome to add more examples for popular mappers, [Guides](https://github.com/MLSDev/TRON/tree/master/Guides) would be a good place to put them into.

We as a company however, don't use any mappers apart from `Codable` and `SwiftyJSON`, so unfortunately have no time for providing documentation for other mappers.
