### ISSUE TITLE
Getting response data from request call

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#28]
Hello,

From the recommended way of doing requests,

`let alamofireRequest = request.perform(withSuccess: { result in }, failure: { error in})`

I can't seem to get the statusCode, header and meta data etc.. only the data. Is there a way to get these? I can't find it in the docs.

**Comment by DenTelezhkin** [comment]
Usually it's not common to parse status code, headers and metadata yourself, since you mostly rely on response or error received. However, TRON provides several ways to access those

1. You can add plugin to request, which will be called on all stages of request happening. https://github.com/MLSDev/TRON/blob/master/Source/Core/Plugin.swift#L32

2. You can perform requests using this method:

```swift
let afRequest = request.performCollectingTimeline(withCompletion: { result in
    print(result.response.statusCode)
    print(result.response.allHeaderFields)
})
```

3. In case your request errors out, all request data is wrapped into `APIError` struct:

```swift
let alamofireRequest = request.perform(withSuccess: { result in }, failure: { error in
    print(error.response.statusCode)
   print(error.response.allHeaderFields)
})
```

Hope this clears out our intention of hiding all this data and leading you right to your data model.
