### ISSUE TITLE
holding strong references with dynamic base url

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#29]
Hi, 

I have an app where every user could have different environments. For every environment there is a different base url. 

Since tron requires to have a strong reference. I don't know how to change the url inside without having to completely close and restart the app.. Do you guys have thought about this use case?

`var tron = TRON(baseURL: UserDefaults.standard.value(forKey: Constants.kAPIUrlUserDefaultsKey) as! String)`

**Comment by DenTelezhkin** [comment]
Sure, you just shouldn't make TRON a singleton object. One good approach for this would be to have a multiton, something like `AppEnvironment`, that has a `current` value, and holds references to all services like TRON. And when your environment changes, you simply replace TRON instance on AppEnvironment and that's it.

The only downside for this would be that all requests that did not have time to hit your API before TRON instance is destroyed, will be cancelled, so that would need some special handling.

**Comment by reshadf** [comment]
Thanks I went with this solution!
