### ISSUE TITLE
In depth example of Download Request

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#31]
Hi, 

The Download Request Example is a little bit weird to implement. Lets say if I download an image, would I do the same as when I would do with a normal request? 

I created this function, but it keeps throwing an error

> /Users/username/xcode/project/project/APISessionManager.swift:33:87: Cannot convert value of type 'DownloadAPIRequest<_, _>' to specified type 'DownloadAPIRequest<InvoiceResponse, MyAppError>'

This is my function 

    func downloadInvoice(id: String) -> DownloadAPIRequest<InvoiceResponse, MyAppError> {
        let url = URL(string: "url/invoice")!
        let destination = DownloadRequest.suggestedDownloadDestination(for: .documentDirectory)
        let request: DownloadAPIRequest<InvoiceResponse, MyAppError> = APIHelper.tron.download(url.absoluteString, to: destination)
        
        return request
    }

and my response model

    struct InvoiceResponse {
        var invoice: UIImage?
    }

Could you give a more in depth example of how to use this correctly? 
- how should the model be build
- how to handle the response 

Thanks in advance!

**Comment by DenTelezhkin** [comment]
Hey!

Lets get obvious stuff out of the way just in case

1. If you download image simply for setting it onto `UIImageView`, you should use AlamofireImage, or SDWebImage, or similar wrapper, because TRON is not lightweight for this task.
2. If you download image and want to have it in memory, and your image is not big, you probably should use `APIRequest` instead of `DownloadAPIRequest`.

`DownloadAPIRequest` is a wrapper around Alamofire download method and serves a purpose of downloading file to disk. 

As for Model, i agree interface is cumbersome right now since most of the time you don't need any model, you just need the file. As a workaround, you can use `EmptyResponse` to not deal with `Model`:

```swift
let request : DownloadAPIRequest<EmptyResponse,MyAppError> = tron.download(url, to: destination)
request.performCollectingTimeline(withCompletion: { response in
    if let url = response.destinationURL?.path {
        let image = UIImage(contentsOfFile: url)
    }
})
```

Hope this helps.
