### ISSUE TITLE
Unable To Use The Dependency On Xcode 9-beta

### ISSUE THREAD

**Issue by tonespy** [MLSDev/TRON#39]
I am using Xcode 9-Beta for development. And I've not been able to utilize the TRON library. Most of the errors are coming from the Alamofire library. I could modify the libraries to work, but it's a project being worked on by more than one person. So, is there a way to have this fixed or I've to go migrate my codebase back to 3.1? 

I installed Alamofire 4.4 and it's working fine. But, the one bundled with TRON is failing when building.

Thanks

**Comment by DenTelezhkin** [comment]
How are you installing TRON, using Carthage or CocoaPods?

**Comment by tonespy** [comment]
@DenHeadless Cocoapods

**Comment by tonespy** [comment]
So, @DenHeadless I had to work from this [commit](https://github.com/MLSDev/TRON/commit/19474c0ec497567696b12d83a53139e0d1b958c3)

There was an error in the UploadAPIRequest file. Which I had to fix for the mean time. It basic and pretty straight forward. And I've not been able to utilize `TRON/RxSwift`

**Previous**
```
let multipartConstructionBlock: (MultipartFormData) -> Void = { requestFormData in
            self.parameters.forEach { (key,value) in
                requestFormData.append(String(describing: value).data(using:.utf8) ?? Data(), withName: key)
            }
            multipartFormDataBlock(requestFormData)
        }
```

**After**
```
let multipartConstructionBlock: (MultipartFormData) -> Void = { requestFormData in
            self.parameters.forEach { (arg) in
                
                let (key, value) = arg
                requestFormData.append(String(describing: value).data(using:.utf8) ?? Data(), withName: key)
            }
            multipartFormDataBlock(requestFormData)
        }
```

**Comment by DenTelezhkin** [comment]
Well, yeah. For now the goal is to be compatible with Swift 3.0 - Swift 3.2.

This error you are mentioning will get reverted in future Xcode 9 beta releases and final release - there's active discussion about this right now - https://www.mail-archive.com/swift-evolution@swift.org/msg26440.html

I would recommend you to use Swift 3.2 for now, if you want to do Xcode 9 development.

That said, next release of TRON, that is planned for autumn release, will hopefully have support for Swift 3.1 - Swift 4, so that you would be able to use it with any toolchain and Swift version you need. 

It's also possible that we'll make a minor release somewhere around beta 3 - beta 4, to make Xcode 8 - Xcode 9 release that is compatible with both versions without warnings. And probably somewhere around that time we'll create a swift4 branch to develop next release.

Let's leave this issue open for now, since this might be a common question for people trying to develop with Xcode 9 right now.

**Comment by DenTelezhkin** [comment]
TRON 3.1.0 should be compatible with Xcode 8 and Xcode 9(beta 6), Swift 3.1, 3.2 and 4. Closing.
