### ISSUE TITLE
headerBuilder deprecated. Warning message on BaseRequest.swift. Xcode9 / Swift4

### ISSUE THREAD

**Issue by agu3rra** [MLSDev/TRON#63]
I'm getting a warning message from the Swift compiler after adding TRON 4.1.0 to my Xcode project. Filename: BaseRequest.swift
Line: 148
`self.headerBuilder = tron.headerBuilder`
'headerBuilder' is deprecated: Global headerBuilder is deprecated and may be removed in future versions of the framework. To have global request customization, please use Alamofire.RequestAdapter - https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#requestadapter

Please ignore and close this item, if that's expected behavior. Thank you.

**Comment by DenTelezhkin** [comment]
Yes, this is related to #62. The thing is, we only want to add functionality on top of Alamofire if it makes framework more convenient and more powerful. However, in case of TRON level header builder we were instead decreasing functionality as compared to RequestAdapter and RequestRetrier. Those wrappers not only allow to modify headers, but other request properties like timeouts etc. And they also allow to retry requests, which of course HeaderBuilder will never be able to do. Which is why we decided to deprecate it to let our users know there is more powerful alternative. 

Closing this one, hope this information helps to understand our motivations.
