### ISSUE TITLE
Sending request with JSON body

### ISSUE THREAD

**Issue by reshadf** [MLSDev/TRON#64]
Hi, Is there a way to send JSON as the request body on a POST call? Or does this happen under the hood automatically on a POST method? 

In Alamofire this is done using `request.httpbody = data`

But I couldn't find an example of how to do this with TRON

**Comment by DenTelezhkin** [comment]
Hi, sure, by default TRON uses [Alamofire.URLEncoding](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L76), so all you need to do is set json encoding on request:

```swift
request.parameterEncoding = JSONEncoding.default
```

And then all parameters specified on request will be serialized as JSON and encoded in HTTP body. Depending on your back-end this may not be required, for example Ruby on Rails is able to automatically collect parameters from both url-encoding and JSON payloads depending on the header being sent.

**Comment by reshadf** [comment]
thanks for the quick response, I tried your solution but this results in an error. ( sidenote: all my objects are codable )

>*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSConcreteData)'

This is what my code looks like now. 

```
func saveEntry(id: String, entryField: [EntryField]) -> ValidationRequest {
        let url = URL(string: "\(prefix)entry/\(id)/update")!
        let request: ValidationRequest = APIHelper.tron.codable.request(url.absoluteString)
        let data = try! JSONEncoder().encode(entryField)
        request.method = .post
        request.parameterEncoding = JSONEncoding.default
        request.parameters["values"] = data
        return request
    }
```

Also, how would this work with uploading? In that case, I have this working code right now but the parameters are sent via query parameters 
```
func saveEntryWithAttachment(id: String, entryField: [EntryField], attachment: UIImage) -> UploadValidationRequest {
        let url = URL(string: "\(prefix)entry/\(id)/update")!
        let imageData = UIImagePNGRepresentation(attachment)
        let request: UploadValidationRequest = APIHelper.tron.codable.uploadMultipart(url.absoluteString, formData: { (formData) in
                guard let imageData = imageData else { return }
                formData.contentType = "multipart/form-data; charset=utf-8; boundary=\(formData.boundary)"
                formData.append(imageData, withName: "attachment", fileName: "attachment.png", mimeType: "image/png")
        })
        let data = try! JSONEncoder().encode(entryField)
        request.method = .post
        request.parameters["values"] = String(data: data, encoding: .utf8)!
        return request
    }
```

**Comment by DenTelezhkin** [comment]
In the first snippet the problem is you are trying to encode fields into NSData, and put it into parameters. What JSONEncoding does, it takes parameters dictionary, and converts it into Data by using JSONSerialization. And per documentation of JSONSerialization:

```swift
All objects are instances of NSString, NSNumber, NSArray, NSDictionary, or NSNull.
```
That's why it crashes - because it can't work with NSData(NSConcreteData in this case). If i understood correctly, you need to send dictionary with one "value" key and array of objects inside. Unfortunately, JSONEncoding expects `[String:Any]` to create Data from it, and JSONEncoder you use for Codable can only output `Data`, which is not what Alamofire or TRON expect. If you don't mind using double conversion, here's something you could do:

```swift
extension Encodable {
  func asArrayOfDictionaries() throws -> [[String: Any]] {
    let data = try JSONEncoder().encode(self)
    guard let array = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [[String: Any]] else {
      throw NSError()
    }
    return array
  }
}
```
And then:

```swift
func saveEntry(id: String, entryField: [EntryField]) -> ValidationRequest {
        let url = URL(string: "\(prefix)entry/\(id)/update")!
        let request: ValidationRequest = APIHelper.tron.codable.request(url.absoluteString)
        request.method = .post
        request.parameterEncoding = JSONEncoding.default
        request.parameters["values"] = try? entryField.asArrayOfDictionaries() ?? []
        return request
    }
```

Or, if you don't like double conversion approach, you can implement custom parameter encoding, and set HTTP body directly, but you need to encode dictionary, and not array of objects, so something like 

```swift
// This is code from Custom Parameter Encoding, so request property is NSURLRequest

request.httpBody = try! JSONEncoder().encode(["values":entryField])
```

I hope this helps) As for second snippet, it's multipart, and sending JSON there is not really a good idea, most of back-end parsers will not understand you, and will expect key-value instead of JSON. Which, at the moment, you use, since multipart-form data POST request will encode all values as key-value.
